name: 'Checkmarx AST Github Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx'
inputs:
  checkmarx_url: #base_uri
    required: true
    description: 'Provide the AST portal URL'
  cx_tenant:
    required: true
    description: 'Provide the Tenant for AST portal URL'
  checkmarx_client_id:
    required: true
    description: 'Client ID for AST portal authentication'
  checkmarx_client_secret: #cx_client_secret
    required: true
    description: 'Secret key for AST portal authentication'
  project: #project_name
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  branch:
    required: false
    default: ${{ github.head_ref || github.ref }} # default branch name
    description: 'Branch name'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  global_params:
    required: false
    default: ''
    description: 'Global parameters applied to all cx commands'
  scan_params:
    required: false
    default: ''
    description: 'Additional parameters for cx scan command only'
  utils_params:
    required: false
    default: ''
    description: 'Additional parameters for cx utils pr command only'
  results_params:
    required: false
    default: ''
    description: 'Additional parameters for cx results show command only'
  additional_params:
    required: false
    default: ''
    description: '[DEPRECATED] Use scan_params instead. Additional parameters for AST scan'
  repo_name:
    required: false
    default:  ${{ github.event.repository.name }}
    description: "Repository name for PR decoration"
  namespace:
    required: false
    default: ${{ github.repository_owner }}
    description: "Organization name to create the Pr comment"
  pr_number:
    required: false
    default: ${{ github.event.number }}
    description: "Pr Number of the pull request that needs the decoration"
  source_dir:
    required: false
    default: .
    description: "Source directory"
  scanner:
    required: false
    default: ''
    description: 'Specify the scanner to be used for the scan (sast, sca, etc.)'
  zip_include:
    required: false
    description: 'Provide zip file include in regex format'
    default: ''
  zip_exclude:
    required: false
    description: 'Provide zip file EXCLUDE (NOT SCAN) in regex format'
    default: ''
  ######### Break Glass ##########
  break_glass_disable_cxflow:
    required: false
    description: 'Set the default to true to disable cxflow'
    default: false
  
outputs: 
  cxcli:
    description: output from cli
  cxScanID:
    description: scan ID output from cli
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.checkmarx_url }}
    - ${{ inputs.cx_tenant }}
    - ${{ inputs.checkmarx_client_id }}
    - ${{ inputs.checkmarx_client_secret }}
    - ${{ inputs.github_token }}
    - ${{ inputs.project }}
    - ${{ inputs.additional_params }}
    - ${{ inputs.global_params }}
    - ${{ inputs.scan_params }}
    - ${{ inputs.utils_params }}
    - ${{ inputs.results_params }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.pr_number }}
    - ${{ inputs.source_dir }}
  entrypoint: '/app/entrypoint.sh'
  post-if: cancelled()
  post-entrypoint: '/app/cleanup.sh'

  env:
    CX_BASE_URI: "${{ inputs.checkmarx_url }}"
    CX_TENANT: ${{ inputs.cx_tenant }}
    CX_CLIENT_ID: ${{ inputs.checkmarx_client_id }}
    CX_CLIENT_SECRET: ${{ inputs.checkmarx_client_secret }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    BRANCH: ${{ inputs.branch }}
    PROJECT_NAME: ${{ inputs.project }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}
    GLOBAL_PARAMS: ${{ inputs.global_params }}
    SCAN_PARAMS: ${{ inputs.scan_params }}
    UTILS_PARAMS: ${{ inputs.utils_params }}
    RESULTS_PARAMS: ${{ inputs.results_params }}
    REPO_NAME: ${{ inputs.repo_name }}
    NAMESPACE: ${{ inputs.namespace }}
    PR_NUMBER: ${{ inputs.pr_number }}
    SOURCE_DIR: ${{ inputs.source_dir }}
    SCANNER: ${{ inputs.scanner }}
    ZIP_INCLUDE: ${{ inputs.zip_include }}
    ZIP_EXCLUDE: ${{ inputs.zip_exclude }}
    BREAK_GLASS_DISABLE_CXFLOW: ${{ inputs.break_glass_disable_cxflow }}
branding:
  icon: 'check'
  color: 'green'
